In [1]:
# coding: utf-8
import tensorflow as tf

# 默认Tensorflow会话
sess = tf.InteractiveSession()

# 对数据进行准备
# 产生一个4x4的矩阵，满足均值为0，标准差为1的正态分布
a = tf.Variable(tf.random_normal([4, 4], mean=0.0, stddev=1.0))

# 对所有变量进行初始化，这里对a进行初始化
tf.global_variables_initializer().run()

# 输出原始的a的值
print"原始矩阵:\n", a.eval()

原始矩阵:
[[-0.4090131  -0.2457109   0.7692419  -0.10311802]
 [-0.18510456  0.5100287   1.9183942  -0.8198766 ]
 [-1.02769    -0.68557066 -0.18391953  0.72068346]
 [ 0.2200638  -0.29648167 -1.7098439  -1.2139964 ]]


In [4]:
# coding: utf-8
# sigmoid激活函数：\frac{1}{1 + e^{-x}}
# 优点：输出限制在0，1之间，如LSTM的门控就必须使用sigmoid
# 缺点：涉及到指数计算，计算量大；容易梯度消失；不关于原点对称
# sigmoid函数处理负数
print "anwser 1:", tf.nn.sigmoid(-2.9).eval()
# sigmoid函数处理正数
print "anwser 2:", tf.nn.sigmoid(3.4).eval()

# 对a使用sigmoid函数进行激活处理，将结果保存到b中
b = tf.nn.sigmoid(a)

# 输出处理后的a，即b的值
print "sigmoid函数激活后的矩阵:\n", b.eval()

anwser 1: 0.05215356
anwser 2: 0.9677046
sigmoid函数激活后的矩阵:
[[0.28072977 0.542763   0.4840443  0.091187  ]
 [0.57963765 0.33234805 0.73203653 0.898169  ]
 [0.38909778 0.6560786  0.5287672  0.58028483]
 [0.25249916 0.2798983  0.08161165 0.4413188 ]]


In [5]:
# coding: utf-8
# tanh激活函数：\frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}
# 解决sigmoid左右对称的问题
# tanh函数处理负数
print "anwser 1:", tf.nn.tanh(-2.9).eval()
# tanh函数处理正数
print "anwser 2:", tf.nn.tanh(3.4).eval()

# 对a使用tanh函数进行激活处理，将结果保存到b中
b = tf.nn.tanh(a)

# 输出处理后的a，即b的值
print "tanh函数激活后的矩阵:\n", b.eval()

anwser 1: -0.9939633
anwser 2: 0.9977749
tanh函数激活后的矩阵:
[[-0.7356101   0.16980994 -0.0637577  -0.98006594]
 [ 0.31066942 -0.60283226  0.7636776   0.97461796]
 [-0.42280796  0.5688813   0.1146892   0.3130676 ]
 [-0.79516643 -0.73749566 -0.9843301  -0.23153566]]


In [6]:
# coding: utf-8
# Relu激活函数：max(0,x)
# 解决sigmoid计算量大，梯度消失的问题，但在负数上梯度为0
# Relu函数处理负数
print "anwser 1:", tf.nn.relu(-2.9).eval()
# Relu函数处理正数
print "anwser 2:", tf.nn.relu(3.4).eval()

# 对a使用Relu函数进行激活处理，将结果保存到b中
b = tf.nn.relu(a)

# 输出处理后的a，即b的值
print "Relu函数激活后的矩阵:\n", b.eval()

anwser 1: 0.0
anwser 2: 3.4
Relu函数激活后的矩阵:
[[0.         0.17147096 0.         0.        ]
 [0.3212862  0.         1.0049797  2.177043  ]
 [0.         0.6458673  0.11519608 0.32394275]
 [0.         0.         0.         0.        ]]


In [6]:
# coding: utf-8
# elu:`exp(x) - 1` if < 0, `x` otherwise.
print tf.nn.elu(a).eval()
# [relu(x), relu(-x)]
print tf.nn.crelu(a).eval()
# min(max(x, 0), 6)
print tf.nn.relu6(a).eval()
# log(exp(x) + 1)
print tf.nn.softplus(a).eval()
# x / (abs(x) + 1)
print tf.nn.softsign(a).eval()

[[-0.6974885  -0.65892005  0.23269276  1.010489  ]
 [ 1.8564698  -0.915025   -0.9290937   1.0934621 ]
 [ 0.9696932   0.77226484  1.6061519   1.3483294 ]
 [ 0.90551883 -0.05563325  0.12308426  0.3264205 ]]
[[0.         0.         0.23269276 1.010489   1.1956359  1.0756383
  0.         0.        ]
 [1.8564698  0.         0.         1.0934621  0.         2.4653983
  2.6463966  0.        ]
 [0.9696932  0.77226484 1.6061519  1.3483294  0.         0.
  0.         0.        ]
 [0.90551883 0.         0.12308426 0.3264205  0.         0.05724066
  0.         0.        ]]
[[0.         0.         0.23269276 1.010489  ]
 [1.8564698  0.         0.         1.0934621 ]
 [0.9696932  0.77226484 1.6061519  1.3483294 ]
 [0.90551883 0.         0.12308426 0.3264205 ]]
[[0.2642943  0.29347524 0.81624657 1.3209406 ]
 [2.0016286  0.08155695 0.06850529 1.3824342 ]
 [1.2911963  1.1520467  1.7890218  1.5791821 ]
 [1.2450806  0.6649363  0.75658184 0.86961746]]
[[-0.54455113 -0.5182205   0.18876785  0.50260854]
 [ 